name: APK Yapici
on: [push]

jobs:
  apk-yap:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Java Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Daha stabil bir sürüm'

      - name: Kutuphaneleri Yukle
        run: |
          pip install -r requirements.txt
          # En stabil sürümü kuruyoruz
          pip install --force-reinstall flet==0.23.2

      - name: APK Derle
        # İkon yolunu flet.yaml'dan alacağı için sadece verbose ekliyoruz
        run: flet build apk --verbose

      - name: Dosyayi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Hilal_kpss_Final
          path: build/apk/app-release.apk
